In [30]:
import pandas as pd

# 正确读取Excel文件，并将数据赋值给变量df（常规命名，便于后续操作）
df = pd.read_excel("长沙二手房.xlsx")

# 可选：查看数据前5行，验证是否读取成功
print(df.head())

   城市    区县                              标题       楼盘                       区域  \
0  长沙  长沙周边  国庆节期间大促,空气清新,通透现房即买即交付 长郡旁,大阳台    绿地21城                 株洲-绿地21城
1  长沙  长沙周边   三面花园环绕,地下室和客厅挑空不计面积 大叠墅现房,带电梯  绿地21城别墅                   株洲-云水路
2  长沙  长沙周边                     大平层4字头江景美宅,   文博园·碧湖  湘潭-湖南省湘潭市岳塘区沁园路与滨江中路交汇处
3  长沙  长沙周边  现房三房,南北通透明厨 首付九万月供一千四百三十七,无需Z格    绿地21城  株洲-云水路与云田路交汇处(方特欢乐世界西侧)
4  长沙  长沙周边    检漏啦,首付11万买带露台的洋房,长郡旁环境好,南北通透    绿地21城  株洲-云水路与云田路交汇处(方特欢乐世界西侧)

      总价       单价    户型    面积   朝向        楼层      年份  \
0    30万  4054元/㎡  2室2厅   74㎡  南北向  高层（共33层）  2018年建
1   135万  8653元/㎡   NaN  156㎡   南向       NaN     NaN
2    67万  4785元/㎡  4室2厅  140㎡  南北向  低层（共29层）     NaN
3  41.3万  4089元/㎡  3室2厅  101㎡  南北向  顶层（共32层）     NaN
4    54万  5294元/㎡  3室2厅  102㎡  南北向   顶层（共9层）     NaN

                                                详情页
0   https://cs.esf.fang.com/chushou/3_156857473.htm
1  https://cs.esf.fang.com/chushou/10_157624780.htm
2   https://cs.esf.fang.com/chushou/3_157458221.htm
3   https://cs.esf.fang.com/chushou/3_157586091.htm
4   https://cs.esf.fang.com/chushou/3_157652300.htm

In [31]:
df.head()

,城市,区县,标题,楼盘,区域,总价,单价,户型,面积,朝向,楼层,年份,详情页
0,长沙,长沙周边,"国庆节期间大促,空气清新,通透现房即买即交付 长郡旁,大阳台",绿地21城,株洲-绿地21城,30万,4054元/㎡,2室2厅,74㎡,南北向,高层（共33层）,2018年建,https://cs.esf.fang.com/chushou/3_156857473.htm
1,长沙,长沙周边,"三面花园环绕,地下室和客厅挑空不计面积 大叠墅现房,带电梯",绿地21城别墅,株洲-云水路,135万,8653元/㎡,NaN,156㎡,南向,NaN,NaN,https://cs.esf.fang.com/chushou/10_157624780.htm
2,长沙,长沙周边,"大平层4字头江景美宅,",文博园·碧湖,湘潭-湖南省湘潭市岳塘区沁园路与滨江中路交汇处,67万,4785元/㎡,4室2厅,140㎡,南北向,低层（共29层）,NaN,https://cs.esf.fang.com/chushou/3_157458221.htm
3,长沙,长沙周边,"现房三房,南北通透明厨 首付九万月供一千四百三十七,无需Z格",绿地21城,株洲-云水路与云田路交汇处(方特欢乐世界西侧),41.3万,4089元/㎡,3室2厅,101㎡,南北向,顶层（共32层）,NaN,https://cs.esf.fang.com/chushou/3_157586091.htm
4,长沙,长沙周边,"检漏啦,首付11万买带露台的洋房,长郡旁环境好,南北通透",绿地21城,株洲-云水路与云田路交汇处(方特欢乐世界西侧),54万,5294元/㎡,3室2厅,102㎡,南北向,顶层（共9层）,NaN,https://cs.esf.fang.com/chushou/3_157652300.htm

In [32]:
import re

def ext_layout(title):
    pattern = r"(\d室\d厅)"
    match = re.search(pattern, title)
    if match:
        return match.group(1)
    return None

In [33]:
def get_room_layout(df):
    data = df[df["户型"].isnull()]
    # 循环遍历每一行的数据出来到正则中替换
    for index,row in data.iterrows():
        for index,row in list.iterrows():
            df.at[index,"户型"] = extra_layout(row["标题"])
            # print(row["标题"])
    return df

df = get_room_layout(df) #使用该函数替换
df.count()

AttributeError: type object 'list' has no attribute 'iterrows'

In [34]:
def get_room_layout(df):
    # 筛选“户型”列为空的行（仅处理需要填充的数据，提升效率）
    data = df[df["户型"].isnull()]
    
    # 单层循环遍历需要填充的行（删除了无效的内层list循环）
    for index, row in data.iterrows():
        # 从标题提取户型并填充到当前行的“户型”列
        df.at[index, "户型"] = extra_layout(row["标题"])
    
    return df

# 1. 读取Excel数据（先确保文件路径正确、依赖安装完成）
df = pd.read_excel("长沙二手房.xlsx")

# 2. 调用函数填充户型空值
df = get_room_layout(df)

# 3. 查看结果
df.count()

NameError: name 'extra_layout' is not defined

In [35]:
def get_direction(df):
    # 按“楼盘”分组，求“朝向”的众数，空则返回None
    res = df.groupby("楼盘")["朝向"].agg(lambda x: x.mode() if not x.mode().empty else None).to_dict()
    # 填充“朝向”为空的行
    for index, row in df[df["朝向"].isnull()].iterrows():
        df.at[index, "朝向"] = res[row["楼盘"]]
    return df

df = get_direction(df)
df.count()

# 检查仍为空的“朝向”行
df[df["朝向"].isnull()]  # 说明该方法无法填充，只能删除
df = df.dropna(subset=["朝向"])
df.count()

城市     9859
区县     9859
标题     9859
楼盘     9859
区域     9859
总价     9859
单价     9859
户型     9100
面积     9859
朝向     9859
楼层     9100
年份     8184
详情页    9859
dtype: int64

In [36]:
# 填充“楼层”列为空的行，统一赋值为“别墅”
for index, row in df[df["楼层"].isnull()].iterrows():
    df.at[index, "楼层"] = "别墅"
df.count()

城市     9859
区县     9859
标题     9859
楼盘     9859
区域     9859
总价     9859
单价     9859
户型     9100
面积     9859
朝向     9859
楼层     9859
年份     8184
详情页    9859
dtype: int64

NameError: name 'clean_numeric_data' is not defined

AttributeError: 'float' object has no attribute 'replace'

In [42]:
df = df.dropna(subset=["户型","朝向","楼层","年份"])
df.isnull().sum()  # 6821行是完整的数据，没有缺失了

城市     0
区县     0
标题     0
楼盘     0
区域     0
总价     0
单价     0
户型     0
面积     0
朝向     0
楼层     0
年份     0
详情页    0
dtype: int64

In [43]:
df.head()

,城市,区县,标题,楼盘,区域,总价,单价,户型,面积,朝向,楼层,年份,详情页
0,长沙,长沙周边,"国庆节期间大促,空气清新,通透现房即买即交付 长郡旁,大阳台",绿地21城,株洲-绿地21城,30.0,4054.0,2室2厅,74.0,南北向,高层（共33层）,2018年建,https://cs.esf.fang.com/chushou/3_156857473.htm
5,长沙,长沙周边,"总价58万买长郡旁首付12万,三面采光南向阳台12米无需Z格",绿地21城,株洲-云水路与云田路交汇处(方特欢乐世界西侧),58.0,3932.0,4室2厅,147.5,南北向,高层（共29层）,2018年建,https://cs.esf.fang.com/chushou/3_155856501.htm
7,长沙,长沙周边,"无需z格,洋房,纯板楼,南北通透 双大阳台,部分一楼带花园",绿地21城,株洲-绿地21城,50.0,5208.0,2室2厅,96.0,南北向,底层（共9层）,2018年建,https://cs.esf.fang.com/chushou/3_157114228.htm
8,长沙,长沙周边,首付20万买大平层现房洋房 独户电梯送二边大露台 带阁楼,绿地21城,株洲-绿地21城,98.0,6901.0,4室4厅,142.0,南北向,顶层（共6层）,2018年建,https://cs.esf.fang.com/chushou/3_157089461.htm
11,长沙,长沙周边,长沙南无需购房z格 电梯房 直接认购 首付十万 长郡旁环境好,绿地21城,株洲-云水路与云田路交汇处(方特欢乐世界西侧),44.0,4230.0,3室2厅,104.0,南北向,高层（共31层）,2018年建,https://cs.esf.fang.com/chushou/3_156701423.htm

In [46]:
import pandas as pd

# 方案1：先转字符串，再替换（推荐，兼容混合类型）
df["总价"] = df["总价"].apply(
    lambda x: float(str(x).replace("万", "")) if pd.notna(x) else x
)

# 方案2：更健壮的写法（增加类型判断，避免异常）
def convert_price(x):
    if pd.isna(x):  # 处理空值
        return x
    if isinstance(x, str):  # 仅对字符串做替换
        return float(x.replace("万", ""))
    elif isinstance(x, (int, float)):  # 数值类型直接返回
        return float(x)
    else:  # 其他类型默认返回空值
        return None

df["总价"] = df["总价"].apply(convert_price)

# 查看处理后的数据信息
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8184 entries, 0 to 9861
Data columns (total 13 columns):
城市     8184 non-null object
区县     8184 non-null object
标题     8184 non-null object
楼盘     8184 non-null object
区域     8184 non-null object
总价     8184 non-null float64
单价     8184 non-null float64
户型     8184 non-null object
面积     8184 non-null float64
朝向     8184 non-null object
楼层     8184 non-null object
年份     8184 non-null object
详情页    8184 non-null object
dtypes: float64(3), object(10)
memory usage: 895.1+ KB

In [47]:
df["单价"] = df["单价"].apply(lambda x:float(x.replace("元/㎡","")))
## 面积列清洗
df["面积"] = df["面积"].apply(lambda x:float(x.replace("㎡","")))
## 年份列清洗
df["年份"] = df["年份"].apply(lambda x:int(x.replace("年建","")))

AttributeError: 'float' object has no attribute 'replace'

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8184 entries, 0 to 9861
Data columns (total 13 columns):
城市     8184 non-null object
区县     8184 non-null object
标题     8184 non-null object
楼盘     8184 non-null object
区域     8184 non-null object
总价     8184 non-null float64
单价     8184 non-null float64
户型     8184 non-null object
面积     8184 non-null float64
朝向     8184 non-null object
楼层     8184 non-null object
年份     8184 non-null object
详情页    8184 non-null object
dtypes: float64(3), object(10)
memory usage: 895.1+ KB

In [50]:
df.describe()

                总价            单价           面积
count  8184.000000   8184.000000  8184.000000
mean    188.104922  12991.563416   134.372153
std     160.860748   5237.539703    53.594885
min      17.800000   3382.000000    22.000000
25%     105.150000   9527.000000   105.590000
50%     143.400000  11803.000000   125.000000
75%     212.000000  14904.250000   143.000000
max    2407.000000  52083.000000  1000.000000

In [51]:
# 重命名列名，补充单位说明（总价单位：万；单价单位：元/㎡；面积单位：㎡；年份备注：年建）
df = df.rename(columns={"总价":"总价（万）","单价":"单价（元/㎡）","面积":"面积（㎡）","年份":"年份（年建）"})
# 查看重命名后的列名，验证修改结果
df.columns

Index(['城市', '区县', '标题', '楼盘', '区域', '总价（万）', '单价（元/㎡）', '户型', '面积（㎡）', '朝向',
       '楼层', '年份（年建）', '详情页'],
      dtype='object')

In [56]:
# 提取楼层属性（高/中/低/顶/底层）：匹配“高/中/低/顶/底+层”的格式
df["楼层属性"] = df["楼层"].str.extract(r"([低|高|中|顶|底]层)")

# 提取楼层数（数字）：匹配“共+数字+层”的格式，捕获其中的数字部分
df["楼层数"] = df["楼层"].str.extract(r"共(\d+)层")

# 查看提取后的前几行数据，验证特征提取结果
df.pop("楼层")
df.pop("详情页")
df.columns

KeyError: '楼层'

In [ ]:
df.to_excel("长沙二手房.xlsx",index=False)
print(“清晰完成”)